### PR TITLE
Ci auto rebase

### PR DESCRIPTION
**Pull request by tdaines42**

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
havent tested it, but logic seems fine to me

LGTM :+1: 

only 2 minor things, please add 4 whitespaces for intentation and i guess you could also remove the first 4 testing/debugging commits

**Comment by kiall** [comment]
Overall, LGTM. Agree with max - lets cleanup the indentation, and ideally rebase to squash the testing commits out of the way.

Testing this will be a little hard, because, `jenkins-library` is special - we can't use the `jenkins-library` logic to checkout `jenkins-library`... But we'll figure that out!

**Comment by kiall** [comment]
[CI: Auto rebase PRs prior to testing](https://trello.com/c/qbJvoPrc/608-ci-auto-rebase-prs-prior-to-testing)

**Comment by kiall** [comment]
So - seems theres some sort of issue - http://jenkins.caasp.suse.net/blue/organizations/jenkins/salt/detail/PR-428/21/pipeline/

**Pull request merged**
