### PR TITLE
Gather admin node logs

### PR DESCRIPTION
**Pull request by kiall**

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
can we use `supportconfig` for that? it might be a bit more complicated to get to the logs (untar; cat logs) but we would be always in sync and don't have to duplicate the log-gathering code

**Comment by kiall** [comment]
> can we use supportconfig for that? it might be a bit more complicated to get to the logs (untar; cat logs) but we would be always in sync and don't have to duplicate the log-gathering code

Yea, for masters and workers, definatly! But for admin, since it's not actually a caasp node, we can't. As soon as we make it a real node, I'd switch to supportconfig!

**Comment by MaximilianMeister** [comment]
> Yea, for masters and workers, definatly! But for admin, since it's not actually a caasp node, we can't. As soon as we make it a real node, I'd switch to supportconfig!

I recently added a section that does admin node specific checks, see https://github.com/kubic-project/supportutils-plugin-suse-caasp/blob/master/suse_caasp#L414

**Comment by kiall** [comment]
@MaximilianMeister nice :) We can delete all the admin node specific code from here as soon we we have a "real" admin node to run that against :)

**Pull request merged**
